spring:
  application:
    name: banking-api

  datasource:
    url: jdbc:postgresql://localhost:5433/banking
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: banking
    open-in-view: false
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.yml
    liquibase-schema: public
    default-schema: banking
    drop-first: false

interest:
  percent: 0.10
  max-multiplier: 2.07