spring:
  application:
    name: banking-api

  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:5433/${POSTGRES_DB:banking}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: banking
    open-in-view: false
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.yml
    liquibase-schema: public
    default-schema: banking
    drop-first: false

interest:
  percent: 0.10
  max-multiplier: 2.07

jwt:
  secret: "dGhpcy1pcy1teS1zZWNyZXQta2V5LWZvci1iYW5raW5nLWFwaQ==" # для тестов
  expiration: 3600000 # 1 час

  # Команда генерации (Linux):
  # openssl rand -base64 32

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  info:
    title: Banking API
    description: REST API для управления пользователями, аккаунтами и переводами
    version: 1.0.0